version: "3"

services:
    # Application: PHP FPM
    app:
        image: mage.app
        build:
            context: .
        container_name: mage.app
        env_file:
            - ./docker/.env
        links:
            - db
            - ftse
            - imdb
        networks:
            - mage.net
        volumes:
            - nfsmount:/www
            - ~/.ssh:/root/.ssh
            - ~/.composer/cache:/root/.composer/cache

    # Database: MySQL
    db:
        image: mysql:8.0.23
        cap_add:
            - SYS_NICE
        container_name: mage.db
        env_file:
            - ./docker/.env
        networks:
            - mage.net
        ports:
            - "3306:3306"
        volumes:
            - mage.db:/var/lib/mysql
		command: mysqld --innodb-buffer-pool-size=1024M
    # Full text search engine: Elasticsearch
    ftse:
        image: elasticsearch:7.6.2
        container_name: mage.ftse
        environment:
            - discovery.type=single-node
        networks:
            - mage.net
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - mage.ftse:/usr/share/elasticsearch/data

    # Web server: NginX
    http:
        image: nginx:1.19.6-alpine
        container_name: mage.http
        links:
            - app
            - db
            - ftse
            - imdb
        networks:
            - mage.net
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nfsmount:/www
            - ./docker/http/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/http/certificates/dev.mage.crt:/usr/local/etc/nginx/ssl/dev.mage.crt
            - ./docker/http/certificates/dev.mage.key:/usr/local/etc/nginx/ssl/dev.mage.key

    # In-memory database: Redis
    imdb:
        image: redis:6.0.10-alpine3.13
        container_name: mage.imdb
        env_file:
            - ./docker/.env
        networks:
            - mage.net
        ports:
            - 6379:6379
        volumes:
            - mage.imdb:/data

    # Message broker: RabbitMQ
    mb:
        image: mage.mb
        build:
            context: .
            dockerfile: Dockerfile-mb
        container_name: mage.mb
        env_file:
            - ./docker/.env
        hostname: mage.mb
        networks:
            - mage.net
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - mage.mb:/var/lib/rabbitmq

networks:
    mage.net:

volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"
    mage.db:
    mage.ftse:
    mage.imdb:
    mage.mb:
